name: Update FanCode Data
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Data from Mobile API
        run: |
          curl -L "https://www.fancode.com/api/v1/content/discover/sports-home" \
          -H "User-Agent: FanCode/3.15.0 (Android 12; Pixel 6)" \
          -H "X-Platform: android" \
          -H "X-Client: mobile" \
          -H "Accept: application/json" \
          -H "Connection: keep-alive" > matches.json
          
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add matches.json
          git commit -m "Bypass Update" || echo "No changes"
          git push origin main
          
